In [2]:
import array
arr=array.array('B',[3,6,9,12,15,18,21])
print("New created array:",end="")
for B in range(0,4):
   print(arr[B],end=" ")

New created array:3 6 9 12 

In [3]:
import pandas as pd
dict={'name':["Shubham","Sam","Bablu","Raj"],
'age':["21","18","16","20"]}
info=pd.DataFrame(dict,index=[True,True,False,True])
print(info)


          name age
True   Shubham  21
True       Sam  18
False    Bablu  16
True       Raj  20


In [4]:
print(info.loc[False])

name    Bablu
age        16
Name: False, dtype: object


In [7]:
import numpy as np
arr= np.arange(16)
print("The original array is:",arr)
#shape of the array is 2 rows and 8 column.
arr= np.arange(32).reshape(4,8)
print("\nreshapedarray\n:",arr)
#shape with array of 4 rows and columns.
arr= np.arange(32).reshape(8,4)
print("\nreshapedarray\n:",arr)



The original array is: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshapedarray
: [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]

reshapedarray
: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
